apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # This matches the label of the Deployment Pods
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 80   # Port in the container
  type: LoadBalancer  # Expose the service externally (if supported)
